### ISSUE TITLE
Container "43a7b9612409" is unhealthy

### ISSUE THREAD

**Issue by asancmat** [directus/directus-docker#44] opened 2018-04-27 07:37 UTC
I'm running docker-compose up and i'm having a problem whith one of the docker containers.

I've the same issue using directus:6.3 and directus:6.4

Digest: sha256:db179c3544d2e84ccc5dbef6d70d793cf2817a48045d7d846f7cfeb8e111afa5
Status: Downloaded newer image for getdirectus/directus:6.4
Creating mysql ... done

ERROR: for directus  Container "43a7b9612409" is unhealthy.
ERROR: Encountered errors while bringing up the project.

**Comment by WellingGuzman** [comment] 2018-04-27 07:43
Hey @asancmat, I have bumped the interval for the check to 5sec, I think this should be enough time. can you update to the latest commit and see if it works this time?

**Comment by esanchma** [comment] 2018-04-27 18:56
I can confirm that setting the healthcheck interval to 5s works for me, when 1s didn't.

**Comment by WellingGuzman** [comment] 2018-04-27 19:01
Thanks @esanchma! I will close it.

At first it was working normal on 1s, but that was too fast and it will depends on the machine or the power it has at the moment, but that combination of 5s (interval), 6s (timeout) and 10 (retries) should do it, otherwise let us know!

**Closed by WellingGuzman** 2018-04-27 19:01 UTC
