### ISSUE TITLE
No adapter available for DB type: DB_TYPE

### ISSUE THREAD

**Issue by chadfawcett** [directus/directus-docker#20] opened 2017-06-14 22:19 UTC
After your most recent release, I get the following error when trying to start directus.

```
Running directus!
wait-for-it: waiting 30 seconds for 172.17.0.2:3306
wait-for-it: 172.17.0.2:3306 is available after 0 seconds

Fatal error: Uncaught 
FrameworkAbstract.php(227) : No adapter available for DB type: DB_TYPE

  thrown in /var/www/html/vendor/directus/migrations/lib/Ruckusing/FrameworkAbstract.php on line 227
```

Appears to be related to #16 

For future releases, could you consider tagging with PATCH versions as well as MAJOR and MINOR? (eg 6.3.1). Otherwise an error like this could cause a production setup to go down.

**Comment by WellingGuzman** [comment] 2017-06-14 22:26
Hey @chadfawcett,

Thanks for the suggestions we are going to tag accordingly to directus version in the future releases.

Do you have a complete log of that error? I tried myself locally and the container rain with no problem, so I would love to reproduce this issue.

**Comment by chadfawcett** [comment] 2017-06-14 23:13
Hmm. I am unable to replicate it locally on my MacBook. It seems to be only happening on my server. `Ubuntu 16.04.2 x64`

![screen shot 2017-06-14 at 4 08 45 pm](https://user-images.githubusercontent.com/3250463/27158551-53fa5d30-511c-11e7-943b-1e2e1693f58a.png)

**Comment by WellingGuzman** [comment] 2017-06-14 23:20
Thanks @chadfawcett, later I will try myself in a Ubuntu machine and get back to you.

**Comment by chadfawcett** [comment] 2017-06-14 23:37
Note: Replicated on Ubuntu 14.04 using Docker 17.03.0-ce

**Comment by awbranch** [comment] 2017-06-15 01:12
Replicated on my MacBook too. Docker: 17.03.1-ce-mac12

![image](https://user-images.githubusercontent.com/108669/27160978-23ca06ea-5146-11e7-80b7-1a86a35d7442.png)

**Comment by laportem** [comment] 2017-06-20 06:48
Also getting the error both running the docker commands manually as well as running docker-compose up.
Any idea on a resolution?

**Comment by WellingGuzman** [comment] 2017-06-20 23:34
No yet @laportem, I will have to take a look again, I will get back to you.

**Comment by canyousayyes** [comment] 2017-06-22 16:11
I have debugged the problem and able to setup Directus docker image 6.3.9 properly.
The root cause of this bug is **missing config file `/var/www/html/api/config.php`**

If you check the Installation guide, you will see the **this is a required step**.
https://docs.getdirectus.com/6.3.6/#Installation

OK, there are 2 ways to solve the problem, depending on how you want to setup Directus.
I tried locally and it works for 6.3.9, it should work on 6.4-rc too.

### Docker-compose way
1. Download the [https://github.com/directus/directus/archive/6.3.9.tar.gz](Directus archive) and extract it into your host environment.
2. `cp /path/to/directus/api/config_sample.php /path/to/directus/api/config.php`
3. In `/path/to/directus/api/config.php`, look for the PHP constant
`define('DB_HOST', 'localhost');`
Change it to `mysql`.
4. Copy a `docker-compose.yml` into your host environment. Uncomment the `links` and `volumes` part.
5. `docker-compose up`. done.

### Standalone container way
1. Create and SSH into the container. `docker run --link mysql:mysql -p 8080:8080 --name directus -ti getdirectus/directus:6.3 /bin/bash`
2. cp /var/www/html/api/config_sample.php /var/www/html/api/config.php
3. In `/var/www/html/api/config.php`, look for the PHP constant
`define('DB_HOST', 'localhost');`
Change it to `mysql`.
4. Execute `run-directus` in the container. Done.

---

@WellingGuzman If you didn't see the problem in your local, probably you have the config file setup.
It's tricky as those files are git ignored. You may need a "really fresh" copy to reproduce the problem.

I am new to Directus too. I think it is a great headless CMS and would fit my use case very well.
But I feel upset when I have to spend a couple of hours debugging before trying it.

Though the installation doc stated the setup, when someone look for the docker image, they are expecting something ready to use immediately.

**Comment by WellingGuzman** [comment] 2017-06-24 23:24
Thank you so much for these details information @canyousayyes, I'd give it a try when I got a change.

If someone has tried and can confirm this solve the issue let us know.

**Comment by truefalse10** [comment] 2017-07-04 14:19
@canyousayyes I tried your docker-compose solution but I still get the `No adapter available for DB type: DB_TYPE` error. It seems like docker-compose does not use the fixed api/config.php from the mounted directus folder or am i missing something?

**Comment by ppounder** [comment] 2017-07-14 12:15
I've not tried this, but could you store the config.php locally alongside the docker-compose.yml and then volume map it:
```
volumes:
      - ./config.php:/var/www/html/api/config.php
```
Will try it later.

**Comment by mdbarr73** [comment] 2017-07-19 16:22
I'm experiencing this issue as well on version 6.4.0. I previously used the config.stub setup and had been working great on previous versions. Is that not implemented, or is there an update on this issue?

Thanks for all your efforts.

**Comment by joshuafinch** [comment] 2017-07-31 10:23
Hi all,

Experiencing this same issue for both 6.3.9 and 6.4.0.
(Using `git clone` on this repo, then running `docker-compose up` with no changes to the current HEAD)

Using MacBook Pro with Docker 17.06.0-ce-mac19

```
Creating mysql ... 
Creating mysql ... done
Creating directus ... 
Creating directus ... done
Attaching to mysql, directus
mysql       | Initializing database
mysql       | 170731 10:16:42 [Note] Ignoring --secure-file-priv value as server is running with --bootstrap.
mysql       | 170731 10:16:42 [Note] /usr/local/mysql/bin/mysqld (mysqld 5.5.57) starting as process 68 ...
directus    | Running directus!
mysql       | 170731 10:16:43 [Note] Ignoring --secure-file-priv value as server is running with --bootstrap.
mysql       | 170731 10:16:43 [Note] /usr/local/mysql/bin/mysqld (mysqld 5.5.57) starting as process 74 ...
directus    | wait-for-it: waiting 30 seconds for mysql:3306
mysql       | 
mysql       | PLEASE REMEMBER TO SET A PASSWORD FOR THE MySQL root USER !
mysql       | To do so, start the server, then issue the following commands:
mysql       | 
mysql       | /usr/local/mysql/bin/mysqladmin -u root password 'new-password'
mysql       | /usr/local/mysql/bin/mysqladmin -u root -h  password 'new-password'
mysql       | 
mysql       | Alternatively you can run:
mysql       | /usr/local/mysql/bin/mysql_secure_installation
mysql       | 
mysql       | which will also give you the option of removing the test
mysql       | databases and anonymous user created by default.  This is
mysql       | strongly recommended for production servers.
mysql       | 
mysql       | See the manual for more instructions.
mysql       | 
mysql       | Please report any problems at http://bugs.mysql.com/
mysql       | 
mysql       | Database initialized
mysql       | MySQL init process in progress...
mysql       | 170731 10:16:43 [Note] --secure-file-priv is set to NULL. Operations related to importing and exporting data are disabled
mysql       | 170731 10:16:43 [Note] mysqld (mysqld 5.5.57) starting as process 84 ...
mysql       | 170731 10:16:43 [Note] Plugin 'FEDERATED' is disabled.
mysql       | 170731 10:16:43 InnoDB: The InnoDB memory heap is disabled
mysql       | 170731 10:16:43 InnoDB: Mutexes and rw_locks use GCC atomic builtins
mysql       | 170731 10:16:43 InnoDB: Compressed tables use zlib 1.2.3
mysql       | 170731 10:16:43 InnoDB: Using Linux native AIO
mysql       | 170731 10:16:43 InnoDB: Initializing buffer pool, size = 128.0M
mysql       | 170731 10:16:43 InnoDB: Completed initialization of buffer pool
mysql       | InnoDB: The first specified data file ./ibdata1 did not exist:
mysql       | InnoDB: a new database to be created!
mysql       | 170731 10:16:43  InnoDB: Setting file ./ibdata1 size to 10 MB
mysql       | InnoDB: Database physically writes the file full: wait...
mysql       | 170731 10:16:43  InnoDB: Log file ./ib_logfile0 did not exist: new to be created
mysql       | InnoDB: Setting log file ./ib_logfile0 size to 5 MB
mysql       | InnoDB: Database physically writes the file full: wait...
mysql       | 170731 10:16:44  InnoDB: Log file ./ib_logfile1 did not exist: new to be created
mysql       | InnoDB: Setting log file ./ib_logfile1 size to 5 MB
mysql       | InnoDB: Database physically writes the file full: wait...
mysql       | InnoDB: Doublewrite buffer not found: creating new
mysql       | InnoDB: Doublewrite buffer created
mysql       | InnoDB: 127 rollback segment(s) active.
mysql       | InnoDB: Creating foreign key constraint system tables
mysql       | InnoDB: Foreign key constraint system tables created
mysql       | 170731 10:16:44  InnoDB: Waiting for the background threads to start
mysql       | MySQL init process in progress...
mysql       | 170731 10:16:45 InnoDB: 5.5.57 started; log sequence number 0
mysql       | 170731 10:16:45 [Warning] 'user' entry 'root@c25089cd3fe7' ignored in --skip-name-resolve mode.
mysql       | 170731 10:16:45 [Warning] 'user' entry '@c25089cd3fe7' ignored in --skip-name-resolve mode.
mysql       | 170731 10:16:45 [Warning] 'proxies_priv' entry '@ root@c25089cd3fe7' ignored in --skip-name-resolve mode.
mysql       | 170731 10:16:45 [Note] Event Scheduler: Loaded 0 events
mysql       | 170731 10:16:45 [Note] mysqld: ready for connections.
mysql       | Version: '5.5.57'  socket: '/tmp/mysql.sock'  port: 0  MySQL Community Server (GPL)
mysql       | Warning: Unable to load '/usr/share/zoneinfo/iso3166.tab' as time zone. Skipping it.
mysql       | Warning: Unable to load '/usr/share/zoneinfo/leap-seconds.list' as time zone. Skipping it.
mysql       | Warning: Unable to load '/usr/share/zoneinfo/zone.tab' as time zone. Skipping it.
mysql       | 170731 10:16:47 [Warning] 'proxies_priv' entry '@ root@c25089cd3fe7' ignored in --skip-name-resolve mode.
mysql       | 170731 10:16:47 [Warning] 'proxies_priv' entry '@ root@c25089cd3fe7' ignored in --skip-name-resolve mode.
mysql       | 
mysql       | 170731 10:16:47 [Note] mysqld: Normal shutdown
mysql       | 
mysql       | 170731 10:16:47 [Note] Event Scheduler: Purging the queue. 0 events
mysql       | 170731 10:16:47  InnoDB: Starting shutdown...
mysql       | 170731 10:16:49  InnoDB: Shutdown completed; log sequence number 1595675
mysql       | 170731 10:16:49 [Note] mysqld: Shutdown complete
mysql       | 
mysql       | 
mysql       | MySQL init process done. Ready for start up.
mysql       | 
mysql       | 170731 10:16:49 [Note] --secure-file-priv is set to NULL. Operations related to importing and exporting data are disabled
mysql       | 170731 10:16:49 [Note] mysqld (mysqld 5.5.57) starting as process 1 ...
mysql       | 170731 10:16:49 [Note] Plugin 'FEDERATED' is disabled.
mysql       | 170731 10:16:49 InnoDB: The InnoDB memory heap is disabled
mysql       | 170731 10:16:49 InnoDB: Mutexes and rw_locks use GCC atomic builtins
mysql       | 170731 10:16:49 InnoDB: Compressed tables use zlib 1.2.3
mysql       | 170731 10:16:49 InnoDB: Using Linux native AIO
mysql       | 170731 10:16:49 InnoDB: Initializing buffer pool, size = 128.0M
mysql       | 170731 10:16:49 InnoDB: Completed initialization of buffer pool
mysql       | 170731 10:16:49 InnoDB: highest supported file format is Barracuda.
mysql       | 170731 10:16:49  InnoDB: Waiting for the background threads to start
mysql       | 170731 10:16:50 InnoDB: 5.5.57 started; log sequence number 1595675
mysql       | 170731 10:16:50 [Note] Server hostname (bind-address): '0.0.0.0'; port: 3306
mysql       | 170731 10:16:50 [Note]   - '0.0.0.0' resolves to '0.0.0.0';
mysql       | 170731 10:16:50 [Note] Server socket created on IP: '0.0.0.0'.
mysql       | 170731 10:16:50 [Warning] 'proxies_priv' entry '@ root@c25089cd3fe7' ignored in --skip-name-resolve mode.
mysql       | 170731 10:16:50 [Note] Event Scheduler: Loaded 0 events
mysql       | 170731 10:16:50 [Note] mysqld: ready for connections.
mysql       | Version: '5.5.57'  socket: '/tmp/mysql.sock'  port: 3306  MySQL Community Server (GPL)
directus    | wait-for-it: mysql:3306 is available after 7 seconds
directus    | 
directus    | Fatal error: Uncaught 
directus    | FrameworkAbstract.php(227) : No adapter available for DB type: DB_TYPE
directus    | 
directus    |   thrown in /var/www/html/vendor/directus/migrations/lib/Ruckusing/FrameworkAbstract.php on line 227
directus exited with code 255
directus    | Running directus!
directus    | wait-for-it: waiting 30 seconds for mysql:3306
directus    | wait-for-it: mysql:3306 is available after 7 seconds
directus    | 
directus    | Fatal error: Uncaught 
directus    | FrameworkAbstract.php(227) : No adapter available for DB type: DB_TYPE
directus    | 
directus    |   thrown in /var/www/html/vendor/directus/migrations/lib/Ruckusing/FrameworkAbstract.php on line 227
directus    | Running directus!
directus    | wait-for-it: waiting 30 seconds for mysql:3306
directus    | wait-for-it: mysql:3306 is available after 0 seconds
directus    | 
directus    | Fatal error: Uncaught 
directus    | FrameworkAbstract.php(227) : No adapter available for DB type: DB_TYPE
directus    | 
directus    |   thrown in /var/www/html/vendor/directus/migrations/lib/Ruckusing/FrameworkAbstract.php on line 227
directus    | Running directus!
directus    | wait-for-it: waiting 30 seconds for mysql:3306
directus    | wait-for-it: mysql:3306 is available after 0 seconds
directus    | 
directus    | Fatal error: Uncaught 
directus    | FrameworkAbstract.php(227) : No adapter available for DB type: DB_TYPE
directus    | 
directus    |   thrown in /var/www/html/vendor/directus/migrations/lib/Ruckusing/FrameworkAbstract.php on line 227
directus exited with code 255
directus    | Running directus!
directus    | wait-for-it: waiting 30 seconds for mysql:3306
directus    | wait-for-it: mysql:3306 is available after 7 seconds
directus    | 
directus    | Fatal error: Uncaught 
directus    | FrameworkAbstract.php(227) : No adapter available for DB type: DB_TYPE
directus    | 
directus    |   thrown in /var/www/html/vendor/directus/migrations/lib/Ruckusing/FrameworkAbstract.php on line 227
directus    | Running directus!
directus    | wait-for-it: waiting 30 seconds for mysql:3306
directus    | wait-for-it: mysql:3306 is available after 0 seconds
directus    | 
directus    | Fatal error: Uncaught 
directus    | FrameworkAbstract.php(227) : No adapter available for DB type: DB_TYPE
directus    | 
directus    |   thrown in /var/www/html/vendor/directus/migrations/lib/Ruckusing/FrameworkAbstract.php on line 227
directus    | Running directus!
directus    | wait-for-it: waiting 30 seconds for mysql:3306
directus    | wait-for-it: mysql:3306 is available after 0 seconds
directus    | 
directus    | Fatal error: Uncaught 
directus    | FrameworkAbstract.php(227) : No adapter available for DB type: DB_TYPE
directus    | 
directus    |   thrown in /var/www/html/vendor/directus/migrations/lib/Ruckusing/FrameworkAbstract.php on line 227
directus    | Running directus!
directus    | wait-for-it: waiting 30 seconds for mysql:3306
directus    | wait-for-it: mysql:3306 is available after 0 seconds
directus    | 
directus    | Fatal error: Uncaught 
directus    | FrameworkAbstract.php(227) : No adapter available for DB type: DB_TYPE
directus    | 
directus    |   thrown in /var/www/html/vendor/directus/migrations/lib/Ruckusing/FrameworkAbstract.php on line 227
directus    | Running directus!
directus    | wait-for-it: waiting 30 seconds for mysql:3306
directus    | wait-for-it: mysql:3306 is available after 0 seconds
directus    | 
directus    | Fatal error: Uncaught 
directus    | FrameworkAbstract.php(227) : No adapter available for DB type: DB_TYPE
directus    | 
directus    |   thrown in /var/www/html/vendor/directus/migrations/lib/Ruckusing/FrameworkAbstract.php on line 227
directus exited with code 255
directus    | Running directus!
directus    | wait-for-it: waiting 30 seconds for mysql:3306
directus    | wait-for-it: mysql:3306 is available after 7 seconds
directus    | 
directus    | Fatal error: Uncaught 
directus    | FrameworkAbstract.php(227) : No adapter available for DB type: DB_TYPE
directus    | 
directus    |   thrown in /var/www/html/vendor/directus/migrations/lib/Ruckusing/FrameworkAbstract.php on line 227
directus    | Running directus!
directus    | wait-for-it: waiting 30 seconds for mysql:3306
directus    | wait-for-it: mysql:3306 is available after 0 seconds
directus    | 
directus    | Fatal error: Uncaught 
directus    | FrameworkAbstract.php(227) : No adapter available for DB type: DB_TYPE
directus    | 
directus    |   thrown in /var/www/html/vendor/directus/migrations/lib/Ruckusing/FrameworkAbstract.php on line 227
directus    | Running directus!
directus    | wait-for-it: waiting 30 seconds for mysql:3306
directus    | wait-for-it: mysql:3306 is available after 0 seconds
directus    | 
directus    | Fatal error: Uncaught 
directus    | FrameworkAbstract.php(227) : No adapter available for DB type: DB_TYPE
directus    | 
directus    |   thrown in /var/www/html/vendor/directus/migrations/lib/Ruckusing/FrameworkAbstract.php on line 227
directus    | Running directus!
directus    | wait-for-it: waiting 30 seconds for mysql:3306
directus    | wait-for-it: mysql:3306 is available after 0 seconds
directus    | 
directus    | Fatal error: Uncaught 
directus    | FrameworkAbstract.php(227) : No adapter available for DB type: DB_TYPE
directus    | 
directus    |   thrown in /var/www/html/vendor/directus/migrations/lib/Ruckusing/FrameworkAbstract.php on line 227
directus    | Running directus!
directus    | wait-for-it: waiting 30 seconds for mysql:3306
directus    | wait-for-it: mysql:3306 is available after 0 seconds
directus    | 
directus    | Fatal error: Uncaught 
directus    | FrameworkAbstract.php(227) : No adapter available for DB type: DB_TYPE
directus    | 
directus    |   thrown in /var/www/html/vendor/directus/migrations/lib/Ruckusing/FrameworkAbstract.php on line 227
directus    | Running directus!
directus    | wait-for-it: waiting 30 seconds for mysql:3306
directus    | wait-for-it: mysql:3306 is available after 0 seconds
directus    | 
directus    | Fatal error: Uncaught 
directus    | FrameworkAbstract.php(227) : No adapter available for DB type: DB_TYPE
directus    | 
directus    |   thrown in /var/www/html/vendor/directus/migrations/lib/Ruckusing/FrameworkAbstract.php on line 227
directus    | Running directus!
directus    | wait-for-it: waiting 30 seconds for mysql:3306
directus    | wait-for-it: mysql:3306 is available after 0 seconds
directus    | 
directus    | Fatal error: Uncaught 
directus    | FrameworkAbstract.php(227) : No adapter available for DB type: DB_TYPE
directus    | 
directus    |   thrown in /var/www/html/vendor/directus/migrations/lib/Ruckusing/FrameworkAbstract.php on line 227
directus exited with code 255
directus    | Running directus!
directus    | wait-for-it: waiting 30 seconds for mysql:3306
directus    | wait-for-it: mysql:3306 is available after 7 seconds
directus    | 
directus    | Fatal error: Uncaught 
directus    | FrameworkAbstract.php(227) : No adapter available for DB type: DB_TYPE
directus    | 
directus    |   thrown in /var/www/html/vendor/directus/migrations/lib/Ruckusing/FrameworkAbstract.php on line 227
directus    | Running directus!
directus    | wait-for-it: waiting 30 seconds for mysql:3306
directus    | wait-for-it: mysql:3306 is available after 0 seconds
directus    | 
directus    | Fatal error: Uncaught 
directus    | FrameworkAbstract.php(227) : No adapter available for DB type: DB_TYPE
directus    | 
directus    |   thrown in /var/www/html/vendor/directus/migrations/lib/Ruckusing/FrameworkAbstract.php on line 227
directus    | Running directus!
directus    | wait-for-it: waiting 30 seconds for mysql:3306
directus    | wait-for-it: mysql:3306 is available after 0 seconds
directus    | 
directus    | Fatal error: Uncaught 
directus    | FrameworkAbstract.php(227) : No adapter available for DB type: DB_TYPE
directus    | 
directus    |   thrown in /var/www/html/vendor/directus/migrations/lib/Ruckusing/FrameworkAbstract.php on line 227
directus    | Running directus!
directus    | wait-for-it: waiting 30 seconds for mysql:3306
directus    | wait-for-it: mysql:3306 is available after 0 seconds
directus    | 
directus    | Fatal error: Uncaught 
directus    | FrameworkAbstract.php(227) : No adapter available for DB type: DB_TYPE
directus    | 
directus    |   thrown in /var/www/html/vendor/directus/migrations/lib/Ruckusing/FrameworkAbstract.php on line 227
directus    | Running directus!
directus    | wait-for-it: waiting 30 seconds for mysql:3306
directus    | wait-for-it: mysql:3306 is available after 0 seconds
directus    | 
directus    | Fatal error: Uncaught 
directus    | FrameworkAbstract.php(227) : No adapter available for DB type: DB_TYPE
directus    | 
directus    |   thrown in /var/www/html/vendor/directus/migrations/lib/Ruckusing/FrameworkAbstract.php on line 227
directus    | Running directus!
directus    | wait-for-it: waiting 30 seconds for mysql:3306
directus    | wait-for-it: mysql:3306 is available after 0 seconds
directus    | 
directus    | Fatal error: Uncaught 
directus    | FrameworkAbstract.php(227) : No adapter available for DB type: DB_TYPE
directus    | 
directus    |   thrown in /var/www/html/vendor/directus/migrations/lib/Ruckusing/FrameworkAbstract.php on line 227
directus    | Running directus!
directus    | wait-for-it: waiting 30 seconds for mysql:3306
directus    | wait-for-it: mysql:3306 is available after 0 seconds
directus    | 
directus    | Fatal error: Uncaught 
directus    | FrameworkAbstract.php(227) : No adapter available for DB type: DB_TYPE
directus    | 
directus    |   thrown in /var/www/html/vendor/directus/migrations/lib/Ruckusing/FrameworkAbstract.php on line 227
directus    | Running directus!
directus    | wait-for-it: waiting 30 seconds for mysql:3306
directus    | wait-for-it: mysql:3306 is available after 0 seconds
directus    | 
directus    | Fatal error: Uncaught 
directus    | FrameworkAbstract.php(227) : No adapter available for DB type: DB_TYPE
directus    | 
directus    |   thrown in /var/www/html/vendor/directus/migrations/lib/Ruckusing/FrameworkAbstract.php on line 227
directus    | Running directus!
directus    | wait-for-it: waiting 30 seconds for mysql:3306
directus    | wait-for-it: mysql:3306 is available after 0 seconds
directus    | 
directus    | Fatal error: Uncaught 
directus    | FrameworkAbstract.php(227) : No adapter available for DB type: DB_TYPE
directus    | 
directus    |   thrown in /var/www/html/vendor/directus/migrations/lib/Ruckusing/FrameworkAbstract.php on line 227
directus exited with code 255
directus    | Running directus!
directus    | wait-for-it: waiting 30 seconds for mysql:3306
directus    | wait-for-it: mysql:3306 is available after 7 seconds
directus    | 
directus    | Fatal error: Uncaught 
directus    | FrameworkAbstract.php(227) : No adapter available for DB type: DB_TYPE
directus    | 
directus    |   thrown in /var/www/html/vendor/directus/migrations/lib/Ruckusing/FrameworkAbstract.php on line 227
directus    | Running directus!
directus    | wait-for-it: waiting 30 seconds for mysql:3306
directus    | wait-for-it: mysql:3306 is available after 0 seconds
directus    | 
directus    | Fatal error: Uncaught 
directus    | FrameworkAbstract.php(227) : No adapter available for DB type: DB_TYPE
directus    | 
directus    |   thrown in /var/www/html/vendor/directus/migrations/lib/Ruckusing/FrameworkAbstract.php on line 227
directus    | Running directus!
directus    | wait-for-it: waiting 30 seconds for mysql:3306
directus    | wait-for-it: mysql:3306 is available after 0 seconds
directus    | 
directus    | Fatal error: Uncaught 
directus    | FrameworkAbstract.php(227) : No adapter available for DB type: DB_TYPE
directus    | 
directus    |   thrown in /var/www/html/vendor/directus/migrations/lib/Ruckusing/FrameworkAbstract.php on line 227
directus    | Running directus!
directus    | wait-for-it: waiting 30 seconds for mysql:3306
directus    | wait-for-it: mysql:3306 is available after 0 seconds
directus    | 
directus    | Fatal error: Uncaught 
directus    | FrameworkAbstract.php(227) : No adapter available for DB type: DB_TYPE
directus    | 
directus    |   thrown in /var/www/html/vendor/directus/migrations/lib/Ruckusing/FrameworkAbstract.php on line 227
directus    | Running directus!
directus    | wait-for-it: waiting 30 seconds for mysql:3306
directus    | wait-for-it: mysql:3306 is available after 0 seconds
directus    | 
directus    | Fatal error: Uncaught 
directus    | FrameworkAbstract.php(227) : No adapter available for DB type: DB_TYPE
directus    | 
directus    |   thrown in /var/www/html/vendor/directus/migrations/lib/Ruckusing/FrameworkAbstract.php on line 227
directus    | Running directus!
directus    | wait-for-it: waiting 30 seconds for mysql:3306
directus    | wait-for-it: mysql:3306 is available after 0 seconds
directus    | 
directus    | Fatal error: Uncaught 
directus    | FrameworkAbstract.php(227) : No adapter available for DB type: DB_TYPE
directus    | 
directus    |   thrown in /var/www/html/vendor/directus/migrations/lib/Ruckusing/FrameworkAbstract.php on line 227
directus    | Running directus!
directus    | wait-for-it: waiting 30 seconds for mysql:3306
directus    | wait-for-it: mysql:3306 is available after 0 seconds
directus    | 
directus    | Fatal error: Uncaught 
directus    | FrameworkAbstract.php(227) : No adapter available for DB type: DB_TYPE
directus    | 
directus    |   thrown in /var/www/html/vendor/directus/migrations/lib/Ruckusing/FrameworkAbstract.php on line 227
directus    | Running directus!
directus    | wait-for-it: waiting 30 seconds for mysql:3306
directus    | wait-for-it: mysql:3306 is available after 0 seconds
directus    | 
directus    | Fatal error: Uncaught 
directus    | FrameworkAbstract.php(227) : No adapter available for DB type: DB_TYPE
directus    | 
directus    |   thrown in /var/www/html/vendor/directus/migrations/lib/Ruckusing/FrameworkAbstract.php on line 227
directus    | Running directus!
directus    | wait-for-it: waiting 30 seconds for mysql:3306
directus    | wait-for-it: mysql:3306 is available after 0 seconds
directus    | 
directus    | Fatal error: Uncaught 
directus    | FrameworkAbstract.php(227) : No adapter available for DB type: DB_TYPE
directus    | 
directus    |   thrown in /var/www/html/vendor/directus/migrations/lib/Ruckusing/FrameworkAbstract.php on line 227
directus    | Running directus!
directus    | wait-for-it: waiting 30 seconds for mysql:3306
directus    | wait-for-it: mysql:3306 is available after 0 seconds
directus    | 
directus    | Fatal error: Uncaught 
directus    | FrameworkAbstract.php(227) : No adapter available for DB type: DB_TYPE
directus    | 
directus    |   thrown in /var/www/html/vendor/directus/migrations/lib/Ruckusing/FrameworkAbstract.php on line 227
directus    | Running directus!
directus    | wait-for-it: waiting 30 seconds for mysql:3306
directus    | wait-for-it: mysql:3306 is available after 0 seconds
directus    | 
directus    | Fatal error: Uncaught 
directus    | FrameworkAbstract.php(227) : No adapter available for DB type: DB_TYPE
directus    | 
directus    |   thrown in /var/www/html/vendor/directus/migrations/lib/Ruckusing/FrameworkAbstract.php on line 227
directus exited with code 255
```

Any potential solutions?

**Comment by joshuafinch** [comment] 2017-07-31 10:50
Figured this out.

So following on from @canyousayyes answer - i found that doing the following gets this docker image to work:

1.  Clone the Directus repo `git clone git@github.com:directus/directus.git`
2. Go to the API subfolder
2. Creating, the `config.php` by copying `config_sample.php`
3. Modifying the `config.php` to change `define('DB_HOST', 'localhost');` to `define('DB_HOST', 'mysql');`
4. `docker-compose up`
5. Navigate to `http://localhost:8080`, login with username `admin@admin.com`, password `admin`.

Hopefully this helps the next person that gets confused :)

Can we perhaps change the readme to reflect the fact that we need to volume map the `git@github.com:directus/directus.git` code. This was the crucial step I somehow missed.

**Comment by WellingGuzman** [comment] 2017-08-02 13:28
Hey, everyone experiencing this issue, @jedimonkey just sent a patch (https://github.com/directus/directus-docker/commit/a4b25278949ed4d7cb2e3dd30d4f8f4d2013f7d4)  for this issue which could have some the problem of the empty `config.php` file.

Please confirm this also fixes the problem for any one experiencing it.

**Comment by laportem** [comment] 2017-08-06 09:09
Patch (a4b2527) makes no different. It works with/without the patch.
As pointed out by @canyousayyes, the trick is to mount both the config.php and configuration.php files.

volumes:
        - ./config.php:/var/www/html/api/config.php
        - ./configuration.php:/var/www/html/api/configuration.php

Good news it works perfectly
Thanks for the help

**Comment by jedimonkey** [comment] 2017-08-08 01:07
@laportem: what do you mean it doesn't make any difference?  It certainly fixes the no adapter error.  The init script is designed to write the config, so @canyousayyes's workaround is working around the bootstrap script.  My patch fixes that it correctly detects blank config files and rebuilds them.  You can still mount the config.php/configuration.php through volumes, which will give you persistent storage of the config whether they are blank or proper (and obviously you can customise it), but I don't believe that is the original intention of this docker was constructed.

**Comment by laportem** [comment] 2017-08-09 02:08
Hi @jedimonkey, just feeding back that with or without the patch I still get the DB issue but the moment I mounted the config.php/configuration.php files it all works. Maybe I am doing something wrong but for me I have to forcefully mount these two config files to get pass the DB issue and get the app running ok.

**Comment by manurana** [comment] 2017-08-14 15:26
Hey folks, did a little hacking, and I am taking a guess at what is happening. I am pretty new to docker (this is my first foray), so request some leeway if I am missing something obvious

Even with the latest commit, the dockerfile `directus/6.4/Dockerfile` has the entry `FROM getdirectus/directus-base-layer:0.0.9`. So even if the patch has been created on the repo, `docker compose` is still pulling the old `directus-base-layer:0.0.9` image, which does not have the fix.
The immediate solution seems to be to create a local image after making this change.
As a permanent solution, a new image needs to be created and published for `directus-base-layer` (which I think is already available with the `latest` tag). Then the dockerfile `directus/6.4/Dockerfile` needs to be changed to refer to this new image.

**Comment by manurana** [comment] 2017-08-14 15:29
On a different note, is there a way to see which github commit was used to create a particular image on docker hub ? I know these don't have a 1:1 relation, but in cases like this, a note of some kind would help a lot.

**Comment by jedimonkey** [comment] 2017-08-15 04:24
Hey @laportem, see @manurana comments above.  I completely forgot that the base would need to be recompiled, as I've been building it all from base.  But based on the build log https://hub.docker.com/r/getdirectus/directus-base-layer/builds/ it was rebuilt.

@manurana you can only typically see the dockerfile that was built with in docker hub, not the files. But it was built after my changes were merged.  My bet is docker hasn't pulled the latest base build, which you can do with `docker pull getdirectus/directus-base-layer:latest` which should refresh the image.  If push comes to shove, remove all you local images and try pulling it down again.

**Comment by manurana** [comment] 2017-08-15 07:22
thanks @jedimonkey !
One small addition: you would also have to update the `directus/x.x/Dockerfile` with the new version of `getdirectus/directus-base-layer`

**Comment by dholbrook86** [comment] 2017-09-01 22:59
Followed the solutions listed here to the book. Still getting the same error.
The whole point of Docker is to get something up and running quickly. 2 hours wasted. Time to move to something else. Hopefully Node support is soon. I'll try this then.

**Comment by WellingGuzman** [comment] 2017-09-10 07:22
Sorry about you wasted time, we've been trying to fix this issue for some time now. Node support won't be soon, but we are planning on start fully developing it.

On the other hand, I've updated the images on docker hub, so hopefully installing the image should be flawless.

Please anyone who can confirm let us know.

Thanks to everyone contributing and helping solve this bug.

**Comment by dholbrook86** [comment] 2017-09-11 18:06
Don't mind me. I was frustrated. Sorry if I was rude. Thanks so much for updating the docker image. I will try blowing everything away and retrying the installation. I can't do it right now, but I just wanted to say thank you and apologize for my last "entitled" post.

**Comment by WellingGuzman** [comment] 2017-10-19 16:23
All good! I will close this issue as it was already fixed as soon as we updated the images (on docker hub).

Thanks everyone!

**Closed by WellingGuzman** 2017-10-19 16:23 UTC
