### ISSUE TITLE
502 Bad Gateway errors during use

### ISSUE THREAD

**Issue by jimcloudman** [directus/directus-docker#1] opened 2016-11-06 00:53 UTC
It seems to come up randomly, but occasionally when using Directus from the docker container I get an error in the browser. The page only says "502 Bad Gateway" when I attempt to go to any page in Directus. The only recourse appears to be restarting the container; Directus works normally for some time after that.

The Docker container logs don't show anything helpful, though I'm new to Docker so I may have missed a source of information. Digging into the components of the container I found it uses Caddy, and the latest update to Caddy (0.9.3) [addresses 502 errors](https://github.com/mholt/caddy/releases/tag/v0.9.3), and this container uses 0.9.2. I tried forking the container to update it to 0.9.3, but I wasn't successful; I have a lot to learn about using Docker it seems.

Let me know if you need more information from me to track down and resolve this!

**Comment by WellingGuzman** [comment] 2016-11-06 14:46
Hey @jimcloudman, Thanks for reporting this, let me ping @luissantos and see what he thinks about this.

**Comment by rwatts3** [comment] 2016-12-08 02:04
also seeing this error as well.

**Comment by tonymke** [comment] 2016-12-20 03:20
It looks like the image's startup script is entirely dependent on some variables existing. I was able to get it running by using the same variables used in the docker-compose yaml.

**Comment by WellingGuzman** [comment] 2016-12-20 17:24
hey @tonymke, would you mind to clarify so other can fix their problem or to send a PR?

**Comment by jcmendez** [comment] 2017-01-16 22:35
+1

**Comment by danielabbatt** [comment] 2017-01-19 09:18
If you set the variables that are configured in the docker-compose.yml file then you get a working result:
     - MYSQL_USER=directus
     - MYSQL_PASSWORD=directus
     - MYSQL_ENV_MYSQL_DATABASE=directus
     - MYSQL_PORT_3306_TCP_ADDR=mysql
     - MYSQL_PORT_3306_TCP_PORT=3306
     - MYSQL_ENV_MYSQL_PASSWORD=directus
     - MYSQL_ENV_MYSQL_USER=directus
Obviously adjust the variables to match your environment

**Comment by jcmendez** [comment] 2017-01-19 10:10
@danielabbatt - I think the OP already went past setting the variables.  He states directus was already running and occasionally gives the bad gateway message.  I'm experiencing a similar issue.  @jimcloudman any luck trying to narrow down when this happens so we can reproduce the issue?

**Comment by danielabbatt** [comment] 2017-01-19 11:11
Ah I see, I wasn't clear on that. Yes I have just noticed mine has done the same, overnight. Also it frequently doesn't respond correctly and so the UI breaks a lot. Running on plain apache it seems to work OK though so don't know if it's something to do with caddy?

**Comment by WellingGuzman** [comment] 2017-01-20 07:48
Hey everyone, I've updated the caddy version to the most recent one, **0.9.4** (https://github.com/directus/directus-docker/commit/37e434bfc6b0c3f088f18133b9481418a483152c)

It should stop the random 502 Bad gateway errors.

Let us know if this works for everyone.

**Comment by Froelund** [comment] 2017-01-21 07:16
hi .
I just tested this fix, and I still have the issue with random 502's.

```
# docker pull getdirectus/directus:6.3
6.3: Pulling from getdirectus/directus
Digest: sha256:1a37563b6980315fa267a88f391c5ba0477d435d4933e767474907c11cd8acd2
Status: Image is up to date for getdirectus/directus:6.3
```

**Comment by Froelund** [comment] 2017-01-21 16:47
Here's some of log-lines from `/var/log/caddy.log'
```
21/Jan/2017:16:35:27 +0000 [ERROR 502 /index.php] write unix @->/var/run/php/php5-fpm.socket: write: broken pipe
21/Jan/2017:16:35:40 +0000 [ERROR 502 /index.php] write unix @->/var/run/php/php5-fpm.socket: write: broken pipe
21/Jan/2017:16:35:47 +0000 [ERROR 502 /index.php] write unix @->/var/run/php/php5-fpm.socket: write: broken pipe
21/Jan/2017:16:37:13 +0000 [ERROR 502 /index.php] write unix @->/var/run/php/php5-fpm.socket: write: broken pipe
21/Jan/2017:16:37:14 +0000 [ERROR 502 /index.php] write unix @->/var/run/php/php5-fpm.socket: write: broken pipe
21/Jan/2017:16:42:29 +0000 [ERROR 502 /api/api.php] fcgi: invalid header version
21/Jan/2017:16:42:29 +0000 [ERROR 502 /api/api.php] fcgi: invalid header version
21/Jan/2017:16:42:29 +0000 [ERROR 502 /api/api.php] fcgi: invalid header version
21/Jan/2017:16:42:29 +0000 [ERROR 502 /api/api.php] fcgi: invalid header version
21/Jan/2017:16:42:30 +0000 [ERROR 502 /api/api.php] fcgi: invalid header version
21/Jan/2017:16:42:30 +0000 [ERROR 502 /api/api.php] fcgi: invalid header version
21/Jan/2017:16:42:31 +0000 [ERROR 502 /api/api.php] fcgi: invalid header version
21/Jan/2017:16:42:31 +0000 [ERROR 502 /api/api.php] fcgi: invalid header version
21/Jan/2017:16:42:31 +0000 [ERROR 502 /api/api.php] fcgi: invalid header version
21/Jan/2017:16:42:31 +0000 [ERROR 502 /api/api.php] fcgi: invalid header version
21/Jan/2017:16:42:31 +0000 [ERROR 502 /api/api.php] fcgi: invalid header version
21/Jan/2017:16:42:32 +0000 [ERROR 502 /api/api.php] fcgi: invalid header version
21/Jan/2017:16:42:32 +0000 [ERROR 502 /api/api.php] fcgi: invalid header version
```

`/var/log/supervisor/caddy_stderr.log` is empty, and `/var/log/supervisor/caddy_stdout.log` does not contain any errors.

**Comment by Froelund** [comment] 2017-01-23 10:32
@WellingGuzman Are you sure using Caddy is the right decision?

**Comment by WellingGuzman** [comment] 2017-01-24 00:51
@Froelund to be honest I've never used it or test Directus under it, and I'm newbie in the Docker world, So for me it's hard to know my way around to fix it.

@luissantos built this docker container, and he decided to use Caddy as it was lightweight and we agreed to create a container that was as light as possible.

We are busy working on the next Directus release (6.4) so I will try my best to dedicate each spare time I will have try to fix the docker.

Could it be the [caddyfile](https://github.com/directus/directus-docker/blob/master/directus-php-fpm/etc/caddy/Caddyfile)?

Any help will be appreciate and we thank you for the logs. 

Thanks everyone.

**Comment by Froelund** [comment] 2017-02-02 04:47
@WellingGuzman Okay - fair enough.

Since @luissantos isn't really reacting to this issue with the Caddy implementation, would you accept a PR where I base directus on top of the PHP official image? I'm not sure how lightweight the container will end up being, but the `7.0-apache` is 158 MB alone. Current directus container is 303 MB.

**Comment by WellingGuzman** [comment] 2017-02-02 06:24
@Froelund Yes I will accept a PR.

We will set the caddy into a different branch while we wait for @luissantos.

Thanks.

**Comment by Froelund** [comment] 2017-02-02 06:49
Great. I'll give it a go.

**Comment by rwatts3** [comment] 2017-02-02 07:57
Awesome thank you !!

**Comment by Froelund** [comment] 2017-02-03 16:53
I made the pull-request #3 , but there doesn't seem to be any automated distribution. I think we would need @luissantos to push to docker hub.

**Comment by luissantos** [comment] 2017-02-04 12:39
@Froelund Could you please have a look at the latest docker container. It is not working for me. 
`
Parse error: syntax error, unexpected '{' in /var/www/html/api/configuration.php on line 72`

I will try to have a look later today.

**Comment by Froelund** [comment] 2017-02-04 13:05
I found the same issue, but I believe it isn't related to docker dist.
There is a [pull-request](https://github.com/directus/directus/pull/1344) for a fix, and it seems @WellingGuzman found that there is an issue with the installation process.

**Comment by luissantos** [comment] 2017-02-04 13:11
@Froelund thanks. I will keep an eye on that pull request.

**Comment by WellingGuzman** [comment] 2017-02-06 21:29
After trying hard what was going on, found the issue it was creating the configuration file using the CLI. I made a fix here: https://github.com/directus/directus/commit/8c1aecd0933a6db295f4636ab1aa327aa8340c21 but it will be tagged on 6.3.7 soon. just trying to squeeze two more thing in the next patch version.

@luissantos please confirm if that commit fixes it.

**Comment by WellingGuzman** [comment] 2017-02-09 16:48
The new Directus path version was released, and the problem (`Parse error: syntax error, unexpected '{' in /var/www/html/api/configuration.php on line 72`) should be fixed.

Let me know. 

The 502 Bad Gateway issue was also solved as it was a issue related to caddy, and it was updated to apache.

Probably we could have multiple options in the future, than just apache. :)

Thanks @luissantos,  @Froelund  and everyone that report and help to debug this issue.

**Closed by WellingGuzman** 2017-02-09 16:48 UTC
Labels: bug, help wanted

**Comment by naeluh** [comment] 2017-06-01 01:42
Hi, 

I am using nginx and getting the 502 on install. 

I am able to get through the installation pages but when I click install I end with a 502.

I will grab some error logs and see what happened.

Is the fix only for apache?

Let me know if I can provide any other info.

thanks

**Comment by WellingGuzman** [comment] 2017-06-01 01:44
This was an issue with caddy, and it was changed to apache.

@naeluh did you create a docker image using nginx?
